"""
Django settings for enlacesMAO project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file (desarrollo local)
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-dev-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("1", "true", "yes")

# Controla el envío del correo de notificación al correo_principal del enlace.
# true (default): se envía al usuario del enlace + correos_notificacion.
# false: solo a los correos_notificacion configurados (útil durante pruebas).
# Desacoplado de DEBUG para no exponer secretos en páginas de error.
MAIL_NOTIFICAR_USUARIO = os.environ.get("MAIL_NOTIFICAR_USUARIO", "true").lower() in (
    "1",
    "true",
    "yes",
)

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# Detrás del proxy de Coolify (Traefik termina TLS): marca la petición como
# segura y permite el check CSRF del login/admin con esquema https.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "")
    .split(",")
    if o.strip()
]

# Auth redirects
LOGIN_URL = "/login/"
LOGOUT_URL = "/logout/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'enlaces_ccg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'enlacesMAO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'enlaces_ccg.context_processors.constantes_globales',
            ],
        },
    },
]

WSGI_APPLICATION = 'enlacesMAO.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

def _config_postgres_por_env():
    """Configura Postgres desde variables de entorno (DB_* o DATABASE_URL).

    Postgres es obligatorio (producción y desarrollo usan contenedores). Si
    faltan las variables se lanza ImproperlyConfigured para fallar rápido en
    lugar de caer silenciosamente a SQLite.
    """
    from urllib.parse import urlparse

    name = os.environ.get("DB_NAME", "").strip()
    url = os.environ.get("DATABASE_URL", "").strip()
    if not name and not url:
        raise ImproperlyConfigured(
            "Base de datos no configurada. Define DATABASE_URL "
            "(o DB_NAME/DB_USER/DB_PASSWORD/DB_HOST/DB_PORT) apuntando a Postgres."
        )

    if url:
        parsed = urlparse(url)
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": name or parsed.path.lstrip("/"),
            "USER": os.environ.get("DB_USER", "") or parsed.username or "",
            "PASSWORD": os.environ.get("DB_PASSWORD", "") or parsed.password or "",
            "HOST": os.environ.get("DB_HOST", "") or parsed.hostname or "localhost",
            "PORT": os.environ.get("DB_PORT", "") or (str(parsed.port) if parsed.port else "5432"),
            "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "0")),
            "OPTIONS": {},
        }

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "0")),
        "OPTIONS": {},
    }


DATABASES = {"default": _config_postgres_por_env()}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-hn'

TIME_ZONE = 'America/Tegucigalpa'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise sirve los estáticos en producción (con compresión y caché).
# No se usa ManifestStaticFilesStorage porque jazzmin referencia un directorio
# ('vendor/bootswatch'), lo que dispara ValueError al renderizar el admin.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# SIG — Configuración vía Admin UI (modelo ConfiguracionSIG)
# ---------------------------------------------------------------------------

# Email configuration — smtplib con TLS (puerto 587)
# Configuración vía Admin UI (modelo ConfiguracionCorreo)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = ''


# ---------------------------------------------------------------------------
# django-jazzmin — Tema y configuración del admin
# ---------------------------------------------------------------------------
JAZZMIN_SETTINGS = {
    # Títulos
    "site_title": "Enlaces CCG",
    "site_header": "Enlaces Autorizados CCG",
    "site_brand": "CCG Honduras",
    "site_description": "Gestión de Enlaces Autorizados del Centro Cívico Gubernamental",
    "site_footer": "Centro Cívico Gubernamental — Honduras",
    "welcome_sign": "Bienvenido al Sistema de Gestión de Enlaces CCG",
    "copyright": "CCG Honduras Ltd",

    # Logo (ruta relativa a static o URL externa)
    "site_logo": None,

    # Colores del tema
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # Links superiores (header)
    "topmenu_links": [
        {"name": "Inicio", "url": "enlaces_ccg:lista_edificios", "permissions": []},
        {"name": "Admin", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    # Panel lateral izquierdo — agrupación de modelos
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "enlaces_ccg",
        "auth",
    ],

    # Iconos para cada app/modelo (usa Font Awesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "auth.User": "fas fa-user",
        "enlaces_ccg.Edificio": "fas fa-building",
        "enlaces_ccg.Institucion": "fas fa-landmark",
        "enlaces_ccg.EnlaceAutorizado": "fas fa-id-card",
        "enlaces_ccg.SyncLog": "fas fa-sync-alt",
        "enlaces_ccg.NivelReferencia": "fas fa-layer-group",
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",

    # Contratar el sidebar en admin
    "related_modal_active": True,

    # Personalización de la UI (CSS custom)
    "custom_css": None,
    "custom_js": None,

    # Links del usuario (esquina superior derecha)
    "usermenu_links": [],

    # Collapse del sidebar en modelos relacionados
    "related_modal_active": True,
}

# Estilos para el sidebar del admin
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}


# ---------------------------------------------------------------------------
# Celery / Redis — cola de tareas en segundo plano
# ---------------------------------------------------------------------------
# Broker y backend usan Redis. En producción se configura vía .env (Coolify).
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", REDIS_URL)

# Serialización JSON (evita dependencias de pickle y problemas de seguridad)
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_TRACK_STARTED = True

# Las operaciones SIG (Playwright/Selenium) DEBEN correr serializadas:
# un solo worker procesa una tarea a la vez (sin prefetch múltiple).
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50

# Timeout por tarea (creación SIG puede tardar). Configurable en segundos.
CELERY_TASK_TIME_LIMIT = int(os.environ.get("CELERY_TASK_TIME_LIMIT", "300"))

# Base actions_path para el beat (no usamos programme por ahora, pero habilitado)
# CELERY_BEAT_SCHEDULE puede definirse aquí si se necesitan tareas periódicas.
