# Generated by Django 6.1 on 2026-08-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del edificio (ej. Torre 1, Cuerpo Bajo A)', max_length=100, unique=True)),
                ('siglas', models.CharField(blank=True, default='', help_text='Siglas abreviadas (ej. T1, CBA)', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción opcional del edificio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(help_text='Valor numérico del nivel (1 = más bajo, 5 = más alto)', unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del nivel', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Detalle del alcance de este nivel de referencia')),
            ],
            options={
                'verbose_name': 'Nivel de Referencia',
                'verbose_name_plural': 'Niveles de Referencia',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de la institución', max_length=200)),
                ('siglas', models.CharField(blank=True, default='', help_text='Siglas de la institución (ej. SESAL, SEPLAN)', max_length=30)),
                ('nivel', models.CharField(choices=[('NACIONAL', 'Nacional'), ('DESCENTRALIZADO', 'Descentralizado'), ('DESCENTRALIZADO_PP', 'Descentralizado — Presupuesto Participativo'), ('AUTONOMO', 'Autónomo'), ('OTRO', 'Otro')], default='NACIONAL', help_text='Nivel administrativo de la institución', max_length=30)),
                ('contacto_nombre', models.CharField(blank=True, default='', help_text='Nombre del contacto institucional', max_length=150)),
                ('contacto_correo', models.EmailField(blank=True, default='', help_text='Correo electrónico del contacto', max_length=254)),
                ('contacto_telefono', models.CharField(blank=True, default='', help_text='Teléfono del contacto', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituciones', to='enlaces_ccg.edificio')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EnlaceAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres completos del enlace', max_length=150)),
                ('primer_apellido', models.CharField(help_text='Primer apellido', max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, default='', help_text='Segundo apellido (opcional)', max_length=100)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='', help_text='Género del enlace', max_length=1)),
                ('cargo', models.CharField(help_text='Cargo que desempeña', max_length=150)),
                ('correo_principal', models.EmailField(help_text='Correo institucional principal', max_length=254)),
                ('correo_secundario', models.EmailField(blank=True, default='', help_text='Correo secundario (opcional)', max_length=254)),
                ('telefono_principal', models.CharField(help_text='Teléfono principal de contacto', max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, default='', help_text='Teléfono secundario (opcional)', max_length=20)),
                ('extension_telefonica', models.CharField(blank=True, default='', help_text='Extensión telefónica interna', max_length=10)),
                ('usuario_sig', models.CharField(blank=True, default='', help_text='Usuario en el Sistema de Información Gerencial', max_length=50)),
                ('default_password_sig', models.CharField(blank=True, default='', help_text='Contraseña por defecto en el SIG', max_length=128)),
                ('nombre_sig', models.CharField(blank=True, default='', help_text='Nombre registrado en el SIG', max_length=100)),
                ('pin_sig', models.CharField(blank=True, default='', help_text='PIN de acceso al SIG', max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', help_text='Estado actual del enlace', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='enlaces_ccg.institucion')),
                ('nivel_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces', to='enlaces_ccg.nivelreferencia')),
            ],
            options={
                'verbose_name': 'Enlace Autorizado',
                'verbose_name_plural': 'Enlaces Autorizados',
                'ordering': ['primer_apellido', 'segundo_apellido', 'nombres'],
            },
        ),
    ]
