# Generated by Django 6.1 on 2026-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlaceautorizado',
            name='nivel_referencia',
            field=models.CharField(blank=True, default='', help_text='Nivel de referencia del enlace', max_length=150),
        ),
        migrations.DeleteModel(
            name='NivelReferencia',
        ),
    ]
