# Generated by Django 6.1 on 2026-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0002_alter_enlaceautorizado_nivel_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceautorizado',
            name='comentarios',
            field=models.TextField(blank=True, default='', help_text='Observaciones o comentarios sobre el enlace'),
        ),
    ]
