# Generated by Django 6.1 on 2026-08-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0003_enlaceautorizado_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlaceautorizado',
            old_name='default_password_sig',
            new_name='password_sig',
        ),
        migrations.AddField(
            model_name='enlaceautorizado',
            name='fecha_alta',
            field=models.DateField(blank=True, help_text='Fecha de alta del enlace', null=True),
        ),
        migrations.AddField(
            model_name='enlaceautorizado',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Fecha de baja del enlace', null=True),
        ),
        migrations.AddField(
            model_name='enlaceautorizado',
            name='fecha_seguimiento',
            field=models.DateField(blank=True, help_text='Fecha de seguimiento', null=True),
        ),
        migrations.AddField(
            model_name='enlaceautorizado',
            name='observaciones_alta',
            field=models.TextField(blank=True, default='', help_text='Observaciones del oficio de alta'),
        ),
        migrations.AddField(
            model_name='enlaceautorizado',
            name='observaciones_baja',
            field=models.TextField(blank=True, default='', help_text='Observaciones del oficio de baja'),
        ),
        migrations.AddField(
            model_name='enlaceautorizado',
            name='observaciones_seguimiento',
            field=models.TextField(blank=True, default='', help_text='Observaciones del oficio de seguimiento'),
        ),
        migrations.AddField(
            model_name='enlaceautorizado',
            name='oficio_alta',
            field=models.CharField(blank=True, default='', help_text='Número de oficio de alta', max_length=100),
        ),
        migrations.AddField(
            model_name='enlaceautorizado',
            name='oficio_baja',
            field=models.CharField(blank=True, default='', help_text='Número de oficio de baja', max_length=100),
        ),
        migrations.AddField(
            model_name='enlaceautorizado',
            name='oficio_seguimiento',
            field=models.CharField(blank=True, default='', help_text='Número de oficio de seguimiento', max_length=100),
        ),
        migrations.AlterField(
            model_name='enlaceautorizado',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', help_text='Estado actual del enlace (Estatus en Dynamics)', max_length=10),
        ),
    ]
