# Generated by Django 6.1 on 2026-08-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0004_rename_default_password_sig_enlaceautorizado_password_sig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto o imagen del edificio', null=True, upload_to='edificios/'),
        ),
    ]
