# Generated by Django 6.1 on 2026-08-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0005_edificio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='edificio',
            field=models.ForeignKey(blank=True, help_text='Edificio donde radica la institución (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones', to='enlaces_ccg.edificio'),
        ),
    ]
