# Generated by Django 6.1 on 2026-08-26 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0006_alter_institucion_edificio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='edificio',
            field=models.ForeignKey(blank=True, help_text='Edificio donde radica la institución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones', to='enlaces_ccg.edificio'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nivel',
            field=models.CharField(blank=True, default='', help_text='Nivel/piso dentro del edificio (ej. PB, Nivel 1, Nivel 5)', max_length=30),
        ),
    ]
