# Generated by Django 6.1 on 2026-08-26 19:47

import django.db.models.deletion
import enlaces_ccg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0007_alter_institucion_edificio_alter_institucion_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', help_text='Estado actual de la institución', max_length=10),
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo adjunto (PDF, imagen, documento, etc.)', upload_to=enlaces_ccg.models.ruta_adjunto)),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre descriptivo del adjunto', max_length=255)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción opcional del documento')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='enlaces_ccg.enlaceautorizado')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-subido_en'],
            },
        ),
    ]
