# Generated by Django 6.1 on 2026-08-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0008_institucion_estado_adjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear usuario'), ('deshabilitar', 'Deshabilitar usuario'), ('habilitar', 'Habilitar usuario')], max_length=20)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('error', 'Error'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('usuario_sig_id', models.CharField(blank=True, default='', help_text='ID del usuario en el SIG después de la creación', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='enlaces_ccg.enlaceautorizado')),
            ],
            options={
                'verbose_name': 'Log de sincronización SIG',
                'verbose_name_plural': 'Logs de sincronización SIG',
                'ordering': ['-creado_en'],
            },
        ),
    ]
