# Generated by Django 6.1 on 2026-08-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0009_synclog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear usuario'), ('deshabilitar', 'Deshabilitar usuario'), ('reactivar', 'Reactivar usuario')], max_length=20),
        ),
    ]
