# Generated by Django 6.1 on 2026-08-27 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0010_alter_synclog_accion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlaceautorizado',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='enlaceautorizado',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces', to='enlaces_ccg.institucion'),
        ),
    ]
