# Generated by Django 6.1 on 2026-08-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0011_remove_enlaceautorizado_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlaceautorizado',
            name='correo_principal',
            field=models.EmailField(blank=True, default='', help_text='Correo institucional principal', max_length=254),
        ),
        migrations.AlterField(
            model_name='enlaceautorizado',
            name='telefono_principal',
            field=models.CharField(blank=True, default='', help_text='Teléfono principal de contacto', max_length=20),
        ),
    ]
