# Generated by Django 6.1 on 2026-08-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0012_alter_enlaceautorizado_correo_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_review', models.CharField(blank=True, default='', help_text="Correo(s) de revisión para creación manual de usuarios SIG cuando falla la automatización. Separe varios correos con ';'.", max_length=500, verbose_name='Correo(s) de revisión (SIG_REVIEW_EMAIL)')),
                ('correo_notificacion', models.CharField(blank=True, default='', help_text="Correo(s) de notificación con credenciales cuando un usuario SIG se crea exitosamente. Separe varios correos con ';'.", max_length=500, verbose_name='Correo(s) de notificación (SIG_NOTIFY_EMAIL)')),
                ('correo_emisor', models.EmailField(blank=True, default='', help_text='Cuenta SMTP que envía los correos (EMAIL_HOST_USER).', max_length=254, verbose_name='Correo emisor (EMAIL_HOST_USER)')),
                ('password_emisor', models.CharField(blank=True, default='', help_text='Contraseña de aplicación de la cuenta emisora (EMAIL_HOST_PASSWORD).', max_length=255, verbose_name='Contraseña emisor (EMAIL_HOST_PASSWORD)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de correo',
                'verbose_name_plural': 'Configuración de correo',
            },
        ),
        migrations.AlterField(
            model_name='synclog',
            name='usuario_sig_id',
            field=models.CharField(blank=True, default='', help_text='ID del usuario en el SIG (informativo; la creación no depende de él)', max_length=20),
        ),
    ]
