# Generated by Django 6.1 on 2026-08-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0013_configuracioncorreo_alter_synclog_usuario_sig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlaceautorizado',
            name='correo_principal',
            field=models.EmailField(blank=True, default='', help_text='Correo institucional principal (único; el SIG no permite duplicados)', max_length=254, null=True, unique=True),
        ),
    ]
