# Generated by Django 6.1 on 2026-08-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0014_alter_enlaceautorizado_correo_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear usuario'), ('deshabilitar', 'Deshabilitar usuario'), ('reactivar', 'Reactivar usuario'), ('actualizar_correo', 'Actualizar correo')], max_length=20),
        ),
    ]
