# Generated by Django 6.1 on 2026-08-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0015_alter_synclog_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='niveles',
            field=models.JSONField(blank=True, default=list, help_text='Niveles/pisos dentro del edificio (ej. ["PB", "Nivel 1", "Nivel 2"])'),
        ),
    ]
