# Generated by Django 6.1 on 2026-08-28 20:46

from django.db import migrations


def convertir_niveles_a_array(apps, schema_editor):
    Institucion = apps.get_model('enlaces_ccg', 'Institucion')
    for inst in Institucion.objects.all():
        valor = inst.nivel
        if isinstance(valor, str) and valor:
            inst.niveles = [valor]
            inst.save(update_fields=['niveles'])
        elif isinstance(valor, str) and not valor:
            inst.niveles = []
            inst.save(update_fields=['niveles'])


def revertir_niveles_a_string(apps, schema_editor):
    Institucion = apps.get_model('enlaces_ccg', 'Institucion')
    for inst in Institucion.objects.all():
        valor = inst.niveles
        if isinstance(valor, list) and valor:
            inst.nivel = valor[0]
            inst.save(update_fields=['nivel'])
        elif isinstance(valor, list) and not valor:
            inst.nivel = ""
            inst.save(update_fields=['nivel'])


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0017_add_niveles_field'),
    ]

    operations = [
        migrations.RunPython(convertir_niveles_a_array, revertir_niveles_a_string),
    ]
