# Generated by Django 6.1 on 2026-08-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0018_migrar_niveles_a_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='nivel',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='niveles',
            new_name='nivel',
        ),
    ]
