# Generated by Django 6.1 on 2026-09-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0022_sembrar_permisos_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', help_text='URL base del SIG (p. ej. https://sig.gia.mx/webapp/).', max_length=500, verbose_name='URL del SIG (SIG_URL)')),
                ('usuario', models.CharField(blank=True, default='', help_text='Usuario para el login automatizado del SIG (SIG_USER).', max_length=150, verbose_name='Usuario (SIG_USER)')),
                ('password', models.CharField(blank=True, default='', help_text='Contraseña para el login automatizado del SIG (SIG_PASSWORD).', max_length=255, verbose_name='Contraseña (SIG_PASSWORD)')),
                ('timeout', models.PositiveIntegerField(blank=True, help_text='Tiempo de espera (segundos) para Playwright (SIG_TIMEOUT).', null=True, verbose_name='Timeout en segundos (SIG_TIMEOUT)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración SIG',
                'verbose_name_plural': 'Configuración SIG',
            },
        ),
        migrations.AlterField(
            model_name='enlaceautorizado',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', help_text='Género del enlace', max_length=1),
        ),
    ]
