# Generated by Django 6.1 on 2026-09-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0023_configuracionsig_alter_enlaceautorizado_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='siglas',
            field=models.CharField(blank=True, default='', help_text='Siglas de la institución (ej. SESAL, SEPLAN)', max_length=60),
        ),
    ]
