# Generated by Django 6.1 on 2026-09-08 16:53

import django.db.models.deletion
from django.db import migrations, models


def copiar_datos_institucion_edificio(apps, schema_editor):
    """Copia institucion.edificio_id + institucion.nivel a la tabla intermedia.

    Cada institución con un edificio asignado genera un registro
    InstitucionEdificio con el nivel que tenía.
    """
    Institucion = apps.get_model("enlaces_ccg", "Institucion")
    InstitucionEdificio = apps.get_model("enlaces_ccg", "InstitucionEdificio")

    for inst in Institucion.objects.all():
        edificio_id = inst.edificio_id
        if not edificio_id:
            continue
        InstitucionEdificio.objects.create(
            institucion_id=inst.pk,
            edificio_id=edificio_id,
            nivel=inst.nivel or [],
        )


def revertir_datos_institucion_edificio(apps, schema_editor):
    """Revierte: toma el primer edificio/nivel de cada institución y lo
    escribe de vuelta en los campos FK (solo de respaldo, podría perder datos
    en el caso multi-edificio)."""
    Institucion = apps.get_model("enlaces_ccg", "Institucion")
    InstitucionEdificio = apps.get_model("enlaces_ccg", "InstitucionEdificio")

    for inst in Institucion.objects.all():
        fila = InstitucionEdificio.objects.filter(institucion_id=inst.pk).first()
        if fila:
            inst.edificio_id = fila.edificio_id
            inst.nivel = fila.nivel or []
        else:
            inst.edificio_id = None
            inst.nivel = []
        inst.save()


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0024_alter_institucion_siglas'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.JSONField(blank=True, default=list, help_text='Niveles/pisos en este edificio (ej. ["PB", "Nivel 1", "Nivel 2"])')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituciones_edificios', to='enlaces_ccg.edificio')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituciones_edificios', to='enlaces_ccg.institucion')),
            ],
            options={
                'verbose_name': 'Institución – Edificio',
                'verbose_name_plural': 'Instituciones – Edificios',
                'unique_together': {('institucion', 'edificio')},
            },
        ),
        migrations.RunPython(
            copiar_datos_institucion_edificio,
            revertir_datos_institucion_edificio,
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='edificio',
        ),
        migrations.AddField(
            model_name='institucion',
            name='edificio',
            field=models.ManyToManyField(blank=True, help_text='Edificio(s) donde radica la institución', related_name='instituciones', through='enlaces_ccg.InstitucionEdificio', to='enlaces_ccg.edificio'),
        ),
    ]
