# Generated by Django 6.1 on 2026-09-08 18:24

import django.db.models.deletion
import enlaces_ccg.models
from django.db import migrations, models


def sembrar_carpeta_por_defecto(apps, schema_editor):
    """Crea la carpeta 'Adjuntos: Nuevos Enlaces MAO' usada por defecto
    en el correo de creación de usuarios del SIG."""
    DocumentoCarpeta = apps.get_model("enlaces_ccg", "DocumentoCarpeta")
    DocumentoCarpeta.objects.update_or_create(
        slug="adjuntos-nuevos-enlaces",
        defaults={
            "nombre": "Adjuntos: Nuevos Enlaces MAO",
            "descripcion": "Documentos que se adjuntan automáticamente "
                           "al correo con credenciales de nuevos usuarios SIG.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0025_institucion_edificio_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador corto y único (solo letras, números, guiones).', max_length=100, unique=True, verbose_name='Identificador (slug)')),
                ('nombre', models.CharField(help_text='Nombre visible de la carpeta.', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción opcional de la carpeta.', verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carpeta de documentos',
                'verbose_name_plural': 'Carpetas de documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo (PDF, imagen, documento, etc.).', upload_to=enlaces_ccg.models.ruta_documento, verbose_name='Archivo')),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre descriptivo del documento.', max_length=255, verbose_name='Nombre')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='enlaces_ccg.documentocarpeta', verbose_name='Carpeta')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.RunPython(sembrar_carpeta_por_defecto, migrations.RunPython.noop),
    ]
