# Generated by Django 6.1 on 2026-09-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0027_renombrar_carpeta_adjuntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la sección.', max_length=200, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición en la que se muestra la sección.', verbose_name='Orden')),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='enlaces_ccg.documentocarpeta', verbose_name='Carpeta')),
            ],
            options={
                'verbose_name': 'Sección de documentos',
                'verbose_name_plural': 'Secciones de documentos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='enlaces_ccg.secciondocumento', verbose_name='Sección'),
        ),
        migrations.AddConstraint(
            model_name='secciondocumento',
            constraint=models.UniqueConstraint(fields=('carpeta', 'nombre'), name='unica_seccion_por_carpeta'),
        ),
    ]
