# Generated by Django 6.1 on 2026-09-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0030_carpeta_una_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncorreo',
            name='default_from_email',
            field=models.EmailField(blank=True, default='', help_text='Dirección From por defecto (opcional, si difiere del emisor).', max_length=254, verbose_name='From por defecto'),
        ),
        migrations.AddField(
            model_name='configuracioncorreo',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.office365.com', help_text='Servidor SMTP (ej. smtp.office365.com).', max_length=200, verbose_name='Servidor SMTP'),
        ),
        migrations.AddField(
            model_name='configuracioncorreo',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, default=587, help_text='Puerto SMTP (ej. 587 para TLS).', null=True, verbose_name='Puerto SMTP'),
        ),
        migrations.AddField(
            model_name='configuracioncorreo',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Usar TLS (STARTTLS) para la conexión.', verbose_name='Usar TLS'),
        ),
        migrations.AddField(
            model_name='configuracionsig',
            name='default_password',
            field=models.CharField(blank=True, default='', help_text='Contraseña por defecto para usuarios SIG creados.', max_length=100, verbose_name='Contraseña por defecto'),
        ),
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='correo_emisor',
            field=models.EmailField(blank=True, default='', help_text='Cuenta SMTP que envía los correos (usuario/remitente).', max_length=254, verbose_name='Correo emisor'),
        ),
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='correo_notificacion',
            field=models.CharField(blank=True, default='', help_text="Correo(s) de notificación con credenciales cuando un usuario SIG se crea exitosamente. Separe varios con ';'.", max_length=500, verbose_name='Correo(s) de notificación'),
        ),
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='correo_review',
            field=models.CharField(blank=True, default='', help_text="Correo(s) de revisión para creación manual de usuarios SIG cuando falla la automatización. Separe varios con ';'.", max_length=500, verbose_name='Correo(s) de revisión'),
        ),
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='password_emisor',
            field=models.CharField(blank=True, default='', help_text='Contraseña de aplicación de la cuenta emisora.', max_length=255, verbose_name='Contraseña emisor'),
        ),
        migrations.AlterField(
            model_name='configuracionsig',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Contraseña para el login automatizado del SIG.', max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='configuracionsig',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Tiempo de espera (segundos) para Playwright.', null=True, verbose_name='Timeout (segundos)'),
        ),
        migrations.AlterField(
            model_name='configuracionsig',
            name='url',
            field=models.CharField(blank=True, default='', help_text='URL base del SIG (p. ej. https://sig.gia.mx/webapp/).', max_length=500, verbose_name='URL del SIG'),
        ),
        migrations.AlterField(
            model_name='configuracionsig',
            name='usuario',
            field=models.CharField(blank=True, default='', help_text='Usuario para el login automatizado del SIG.', max_length=150, verbose_name='Usuario'),
        ),
    ]
