# Generated by Django 6.1 on 2026-09-11 15:36

from django.db import migrations, models


def _backfill_sincronizado(apps, schema_editor):
    """Marca como sincronizados los enlaces con creación SIG exitosa registrada."""
    EnlaceAutorizado = apps.get_model("enlaces_ccg", "EnlaceAutorizado")
    SyncLog = apps.get_model("enlaces_ccg", "SyncLog")
    ids = (
        SyncLog.objects.filter(accion="crear", estado="exitoso")
        .values_list("enlace_id", flat=True)
        .distinct()
    )
    EnlaceAutorizado.objects.filter(pk__in=list(ids)).update(sincronizado=True)


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0031_add_smtp_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceautorizado',
            name='sincronizado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario fue creado/sincronizado en el SIG (se marca automáticamente al crear con éxito, o manualmente).', verbose_name='Sincronizado con SIG'),
        ),
        migrations.RunPython(_backfill_sincronizado, migrations.RunPython.noop),
    ]
