# Generated by Django 6.1 on 2026-09-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0032_enlaceautorizado_sincronizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='imagen',
        ),
    ]
