# Generated by Django 6.1 on 2026-09-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0033_remove_edificio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicadoCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de la persona', max_length=200)),
                ('cargo', models.CharField(blank=True, default='', help_text='Cargo dentro de la institución', max_length=120)),
                ('correo', models.EmailField(blank=True, default='', help_text='Correo institucional de contacto', max_length=254, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(blank=True, help_text='Institución a la que pertenece', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_cc', to='enlaces_ccg.institucion')),
            ],
            options={
                'verbose_name': 'Comunicado CC',
                'verbose_name_plural': 'Comunicados CC',
                'ordering': ['nombre'],
            },
        ),
    ]
