# Generated by Django 6.1 on 2026-09-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0034_comunicadocc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_reporte', models.CharField(blank=True, default='/admin/Solicitud/SeguimientoAtencion', help_text='Ruta del reporte de seguimiento de solicitudes en el SIG.', max_length=500, verbose_name='URL del reporte')),
                ('hoja_excel', models.CharField(blank=True, default='', help_text='Nombre de la hoja del Excel. Vacío = auto-detectar la primera.', max_length=100, verbose_name='Hoja del Excel')),
                ('fecha_desde_completa', models.CharField(blank=True, default='01/01/2020', help_text="Fecha 'desde' para la descarga completa (dd/mm/aaaa). El SIG asume que 'hasta' es hoy. En la descarga rápida no se usa.", max_length=20, verbose_name='Fecha desde (completa)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de tickets',
                'verbose_name_plural': 'Configuración de tickets',
            },
        ),
    ]
