# Generated by Django 6.1 on 2026-09-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0035_configuraciontickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('parcial', 'Parcial (rápida)'), ('completo', 'Completo (histórico)')], default='parcial', max_length=10, verbose_name='Modo')),
                ('estado', models.CharField(blank=True, default='', max_length=10, verbose_name='Estado')),
                ('mensaje', models.TextField(blank=True, default='', verbose_name='Mensaje')),
                ('creados', models.PositiveIntegerField(default=0, verbose_name='Creados')),
                ('actualizados', models.PositiveIntegerField(default=0, verbose_name='Actualizados')),
                ('archivados', models.PositiveIntegerField(default=0, verbose_name='Archivados')),
                ('errores', models.PositiveIntegerField(default=0, verbose_name='Errores')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Bitácora de tickets',
                'verbose_name_plural': 'Bitácora de tickets',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='descarga_completa_horas',
            field=models.JSONField(blank=True, default=list, help_text='Horas del día para la descarga completa, ej. ["07:00", "19:00"].', verbose_name='Horas de descarga completa'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Si desmarcado, el tick automático no descarga ni sincroniza.', verbose_name='Sincronización habilitada'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='intervalo_minutos',
            field=models.PositiveSmallIntegerField(default=5, help_text='Cadencia mínima (minutos) entre sincronizaciones parciales.', verbose_name='Intervalo parcial (minutos)'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='modo_default',
            field=models.CharField(choices=[('parcial', 'Parcial (rápida)'), ('completo', 'Completo (histórico)')], default='parcial', help_text="Modo usado por el tick y por 'Sincronizar ahora' sin indicar modo.", max_length=10, verbose_name='Modo por defecto'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Total de tickets'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='ultima_sincronizacion',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última sincronización'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='ultimo_estado',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, verbose_name='Último estado'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='ultimo_mensaje',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Último mensaje'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='ultimo_modo',
            field=models.CharField(blank=True, default='', editable=False, max_length=10),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(help_text="Clave única del SIG: columna 'ID Solicitud servicio'.", max_length=100, unique=True, verbose_name='ID de solicitud')),
                ('numero', models.CharField(blank=True, default='', help_text='Número visible en el SIG (ej. SS20-0459), sin sufijo.', max_length=60, verbose_name='Número')),
                ('numero_display', models.CharField(blank=True, db_index=True, default='', help_text='Número visible con sufijo -N para duplicados (SS20-0459-2).', max_length=60, verbose_name='Número visible')),
                ('solicitud_tipo', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo de solicitud')),
                ('fecha', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('estatus', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', max_length=8, verbose_name='Estatus')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción / asunto')),
                ('archivado', models.BooleanField(db_index=True, default=False, verbose_name='Archivado')),
                ('ultima_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Datos crudos del SIG')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ('-fecha', 'ticket_id'),
                'indexes': [models.Index(fields=['estatus', 'fecha'], name='tick_estatus_fecha'), models.Index(fields=['numero', 'ticket_id'], name='tick_numero_id')],
            },
        ),
    ]
