# Generated by Django 6.1 on 2026-09-16 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0036_ticketlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=500, verbose_name='Descripción de lo sucedido')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='enlaces_ccg.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de seguimiento',
                'verbose_name_plural': 'Registros de seguimiento',
                'ordering': ('-creado_en',),
            },
        ),
    ]
