# Generated by Django 6.1 on 2026-09-17 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0037_ticketregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=400, unique=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Falla',
                'verbose_name_plural': 'Fallas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Servicio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='enlaces_ccg.institucion', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nivel',
            field=models.CharField(blank=True, default='', help_text='Nivel del reporte (columna grupo del SIG, ej. Nivel 8).', max_length=60, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='enlaces_ccg.enlaceautorizado', verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre tal cual viene del SIG cuando no empata con un enlace.', max_length=200, verbose_name='Solicitante (nombre SIG)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='torre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='enlaces_ccg.edificio', verbose_name='Edificio / torre'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='enlaces_ccg.falla', verbose_name='Falla'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='enlaces_ccg.servicio', verbose_name='Servicio'),
        ),
    ]
