# Generated by Django 6.1 on 2026-09-17 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0038_falla_servicio_ticket_institucion_ticket_nivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nivel')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='nivel',
        ),
        migrations.AddField(
            model_name='ticket',
            name='nivel',
            field=models.ForeignKey(blank=True, help_text='Nivel del reporte (columna grupo del SIG, ej. Nivel 8).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='enlaces_ccg.nivel', verbose_name='Nivel'),
        ),
    ]
