# Generated by Django 6.1 on 2026-09-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0039_nivel_alter_ticket_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Responsable de atención',
                'verbose_name_plural': 'Responsables de atención',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='responsable_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='enlaces_ccg.responsableatencion', verbose_name='Responsable de atención'),
        ),
    ]
