# Generated by Django 6.1 on 2026-09-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0040_add_responsable_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='visible',
            field=models.BooleanField(default=True, help_text='Marque si desea que este edificio aparezca en la lista pública', verbose_name='Visible en directorio'),
        ),
    ]
