# Generated by Django 6.1 on 2026-09-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0041_edificio_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontickets',
            name='ultimo_intento',
            field=models.DateTimeField(blank=True, editable=False, help_text='Última corrida (exitosa o fallida). Se usa para el intervalo.', null=True, verbose_name='Último intento'),
        ),
        migrations.AlterField(
            model_name='configuraciontickets',
            name='ultima_sincronizacion',
            field=models.DateTimeField(blank=True, editable=False, help_text='Última corrida EXITOSA. No se actualiza si la sincronización falla.', null=True, verbose_name='Última sincronización'),
        ),
    ]
