# Generated by Django 6.1 on 2026-09-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0042_configuraciontickets_ultimo_intento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontickets',
            name='dias_semana',
            field=models.JSONField(blank=True, default=list, help_text='Días en que corre la sincronización parcial: 0=lunes … 6=domingo. Vacío = todos los días.', verbose_name='Días permitidos (parcial)'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Fin del horario en que corre la sincronización parcial (hora local). Vacío = sin límite.', null=True, verbose_name='Hora fin (parcial)'),
        ),
        migrations.AddField(
            model_name='configuraciontickets',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Inicio del horario en que corre la sincronización parcial (hora local). Vacío = sin límite. La descarga completa no usa este horario.', null=True, verbose_name='Hora inicio (parcial)'),
        ),
    ]
