# Generated by Django 6.1 on 2026-09-18 21:50

import django.db.models.deletion
import enlaces_ccg.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0044_sembrar_cap_atender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo adjunto (PDF, imagen, documento, etc.)', upload_to=enlaces_ccg.models.ruta_ticket_adjunto, verbose_name='Archivo')),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre descriptivo del adjunto', max_length=255, verbose_name='Nombre')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Subido en')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierre_adjuntos', to='enlaces_ccg.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Adjunto de cierre',
                'verbose_name_plural': 'Adjuntos de cierre',
                'ordering': ('-subido_en',),
            },
        ),
        migrations.CreateModel(
            name='TicketCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de atención')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('diagnostico', models.TextField(blank=True, default='', verbose_name='Diagnóstico')),
                ('actividades', models.TextField(blank=True, default='', verbose_name='Actividades realizadas')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('observaciones_usuario', models.TextField(blank=True, default='', verbose_name='Observaciones del usuario')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='enlaces_ccg.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Cierre de ticket',
                'verbose_name_plural': 'Cierres de ticket',
            },
        ),
    ]
