# Generated by Django 6.1 on 2026-09-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0045_ticketadjunto_ticketcierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisogrupo',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text='Descripción opcional del rol.', max_length=255, verbose_name='Descripción'),
        ),
    ]
