# Generated by Django 6.1 on 2026-09-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0046_permisogrupo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisogrupo',
            name='seccion',
            field=models.CharField(blank=True, choices=[('directorio', 'Directorio de Enlaces'), ('tickets', 'Seguimiento de tickets'), ('importar', 'Importaciones'), ('revisiones', 'Modulo Operativo MAO'), ('admin', 'Administración')], default='', help_text='Sección en la que se agrupa este rol en la lista de grupos.', max_length=40, verbose_name='Sección'),
        ),
    ]
