# Generated by Django 6.1 on 2026-09-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0047_permisogrupo_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisogrupo',
            name='seccion',
            field=models.CharField(blank=True, default='', help_text='Sección en la que se agrupa este rol en la lista de grupos. Puedes escribir una nueva o elegir una existente.', max_length=80, verbose_name='Sección'),
        ),
    ]
