# Generated by Django 6.1 on 2026-09-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0048_alter_permisogrupo_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisogrupo',
            name='indice',
            field=models.IntegerField(default=0, help_text='Orden del grupo dentro de su sección (menor primero).', verbose_name='Índice'),
        ),
    ]
