# Generated by Django 6.1 on 2026-09-21 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0049_permisogrupo_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='falla',
            name='clasificacion',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='falla',
            name='fecha_ultima',
            field=models.DateTimeField(blank=True, help_text='Fecha de la solicitud más reciente que definió los datos de la falla.', null=True, verbose_name='Última actualización desde tickets'),
        ),
        migrations.AddField(
            model_name='falla',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas', to='enlaces_ccg.servicio', verbose_name='Servicio'),
        ),
    ]
