# Generated by Django 6.1 on 2026-09-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0050_falla_categoria_falla_clasificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='kpi',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='KPI'),
        ),
    ]
