# Generated by Django 6.1 on 2026-09-22 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0051_falla_kpi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='responsableatencion',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='responsables_atencion', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios asignados'),
        ),
    ]
