# Generated by Django 6.1 on 2026-09-22 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0052_responsableatencion_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(db_index=True, default='tickets', max_length=30)),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('parametros', models.JSONField(default=dict, verbose_name='Parámetros')),
                ('es_predeterminada', models.BooleanField(default=False, verbose_name='Predeterminada')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas_guardadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vista guardada',
                'verbose_name_plural': 'Vistas guardadas',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'modulo', 'nombre')},
            },
        ),
    ]
