# Generated by Django 6.1 on 2026-09-22 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _crear_vista_general(apps, schema_editor):
    VistaGuardada = apps.get_model("enlaces_ccg", "VistaGuardada")
    VistaGuardada.objects.update_or_create(
        modulo="tickets",
        nombre="Mis tickets del mes (abiertos)",
        usuario_id=None,
        defaults={
            "es_general": True,
            "es_predeterminada": False,
            "parametros": {
                "estatus": ["ABIERTO"],
                "responsable": ["@mios"],
                "desde": ["@mes_inicio"],
                "hasta": ["@mes_fin"],
            },
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0053_vistaguardada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vistaguardada',
            name='es_general',
            field=models.BooleanField(default=False, verbose_name='Disponible para todos'),
        ),
        migrations.AlterField(
            model_name='vistaguardada',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vistas_guardadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.RunPython(
            _crear_vista_general, migrations.RunPython.noop
        ),
    ]
