# Generated by Django 6.1 on 2026-09-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0054_vistaguardada_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='enlaces_ccg.responsableatencion', verbose_name='Responsables de atención'),
        ),
    ]
