# Generated by Django 6.1 on 2026-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0055_servicio_responsables'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion_contractual',
            field=models.CharField(blank=True, choices=[('obligatorios_no_comerciales', 'Servicios Obligatorios No Comerciales'), ('obligatorios_comerciales', 'Servicios Obligatorios Comerciales'), ('opcionales_comerciales', 'Servicios Opcionales Comerciales'), ('solicitud_adicional', 'Solicitud Adicional')], default='', max_length=60, verbose_name='Descripción Contractual'),
        ),
    ]
