# Generated by Django 6.1 on 2026-09-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0056_servicio_descripcion_contractual'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisogrupo',
            name='modulos',
            field=models.JSONField(blank=True, default=None, help_text='Claves de módulos (vistas del menú) habilitados para el grupo. None = todos los módulos de las secciones habilitadas.', null=True, verbose_name='Módulos'),
        ),
    ]
