# Generated by Django 6.1 on 2026-09-22 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0057_permisogrupo_modulos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_observacion', 'En observación'), ('validacion_sig', 'Validación SIG'), ('corregido', 'Corregido')], db_index=True, default='en_observacion', max_length=20, verbose_name='Estado')),
                ('tipo_recepcion_corregido', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo de recepción corregido')),
                ('fecha_recepcion_corregida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de recepción corregida')),
                ('observaciones_creacion', models.TextField(blank=True, default='', verbose_name='Observaciones de creación')),
                ('corregido_en', models.DateTimeField(blank=True, null=True, verbose_name='Corregido en')),
                ('cambio_sig_en', models.DateTimeField(blank=True, null=True, verbose_name='Cambio en SIG en')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cambio_sig_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_cambio_sig', to=settings.AUTH_USER_MODEL, verbose_name='Cambio en SIG por')),
                ('corregido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_corregidas', to=settings.AUTH_USER_MODEL, verbose_name='Corregido por')),
                ('responsable_creacion', models.ForeignKey(blank=True, help_text='Usuario del grupo Operador MAO, o vacío = N/A.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_creacion', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de creación')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='enlaces_ccg.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Revisión de ticket',
                'verbose_name_plural': 'Revisiones de ticket',
                'ordering': ('-actualizado_en',),
            },
        ),
    ]
