# Generated by Django 6.1 on 2026-09-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0058_revisionticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionticket',
            name='apertura_antes',
            field=models.DateTimeField(blank=True, help_text='Hora de apertura del ticket cuando se marcó «Cambio en SIG»; sirve para detectar si el SIG ya la actualizó.', null=True, verbose_name='Apertura al marcar Validación SIG'),
        ),
    ]
