# Generated by Django 6.1 on 2026-09-22 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0059_revisionticket_apertura_antes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('timbres', models.PositiveIntegerField(blank=True, help_text='Cantidad de timbres antes de contestar la llamada.', null=True, verbose_name='Timbres antes de contestar')),
                ('asignado_en', models.DateTimeField(blank=True, null=True, verbose_name='Asignado en')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('responsable_creacion', models.ForeignKey(blank=True, help_text='Usuario del grupo Operador MAO, o vacío = N/A.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_llamada', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de creación')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atencion_llamada', to='enlaces_ccg.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Atención de llamada',
                'verbose_name_plural': 'Atenciones de llamadas',
                'ordering': ('-actualizado_en',),
            },
        ),
    ]
