# Generated by Django 6.1 on 2026-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0060_atencionllamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='falla',
            name='seguimiento',
            field=models.BooleanField(default=False, verbose_name='Seguimiento'),
        ),
    ]
