# Generated by Django 6.1 on 2026-09-23 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0062_falla_seguimiento_todas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('diagnostico', models.TextField(blank=True, default='', verbose_name='Diagnóstico')),
                ('actividades', models.TextField(blank=True, default='', verbose_name='Actividades realizadas')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('observaciones_internas', models.TextField(blank=True, default='', verbose_name='Observaciones internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_respuesta', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plantilla de respuesta',
                'verbose_name_plural': 'Plantillas de respuesta',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nombre'), name='plantilla_usuario_nombre_unico')],
            },
        ),
    ]
