# Generated by Django 6.1 on 2026-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0063_plantillarespuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcierre',
            name='proceso',
            field=models.CharField(choices=[('atencion', 'Atención'), ('programacion', 'Programación'), ('tiempo_acordado', 'Tiempo Acordado')], default='atencion', max_length=20, verbose_name='Proceso'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_edificio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Edificio'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_enlace',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del enlace'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_fecha_solucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de la solución final'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_firma',
            field=models.TextField(blank=True, default='', help_text='Imagen PNG (base64) capturada en el dispositivo.', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_institucion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de la programación'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_nivel',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_sin_provisional',
            field=models.TextField(blank=True, default='', verbose_name='Indicación de por qué no aplica solución provisional'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_ubicacion_adicional',
            field=models.CharField(blank=True, default='', help_text='Dato adicional de texto deseado por el usuario (ej. Oficina 21).', max_length=200, verbose_name='Ubicación adicional'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='tiempo_fecha_solucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la solución final'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='tiempo_motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo del tiempo acordado'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='tiempo_solucion_provisional',
            field=models.TextField(blank=True, default='', verbose_name='Solución provisional acordada'),
        ),
    ]
