# Generated by Django 6.1 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0064_ticketcierre_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_firma_fecha',
            field=models.DateTimeField(blank=True, help_text='Respaldo: fecha y hora en que se registró la firma.', null=True, verbose_name='Fecha de la firma'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_firma_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre escrito por el usuario para la firma tipo carta.', max_length=200, verbose_name='Nombre escrito de la firma'),
        ),
        migrations.AddField(
            model_name='ticketcierre',
            name='programacion_firma_usuario',
            field=models.CharField(blank=True, default='', help_text='Respaldo: usuario que registró la firma.', max_length=200, verbose_name='Firmado por'),
        ),
    ]