# Generated by Django 6.1 on 2026-09-23 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0065_ticketcierre_programacion_firma_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.TextField(blank=True, default='', help_text='Imagen PNG (base64) de la firma guardada.', verbose_name='Firma')),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre escrito por el usuario para la firma tipo carta.', max_length=200, verbose_name='Nombre escrito de la firma')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizada en')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_guardada', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Firma guardada',
                'verbose_name_plural': 'Firmas guardadas',
            },
        ),
    ]
