# Generated by Django 6.1 on 2026-09-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces_ccg', '0066_firmausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcierre',
            name='tiempo_fecha_solucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de la solución final'),
        ),
    ]
